# Generated by Django 6.0.8 on 2026-09-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proprietes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(default='France', max_length=100, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='property',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Appartement'), ('house', 'Maison'), ('commercial', 'Commercial'), ('parking', 'Parking'), ('land', 'Terrain')], max_length=20, verbose_name='Type de bien'),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_area',
            field=models.DecimalField(decimal_places=2, help_text='Surface totale en m²', max_digits=8, verbose_name='Surface totale'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(blank=True, null=True, verbose_name='Année de construction'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Légende'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to='properties/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='area',
            field=models.DecimalField(decimal_places=2, help_text='Surface en m²', max_digits=6, verbose_name='Surface'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='available_from',
            field=models.DateField(blank=True, null=True, verbose_name='Disponible à partir de'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='bathrooms',
            field=models.IntegerField(default=0, verbose_name='Salles de bain'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='bedrooms',
            field=models.IntegerField(default=0, verbose_name='Chambres'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Étage'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='rooms',
            field=models.IntegerField(default=0, verbose_name='Pièces'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Occupé'), ('maintenance', 'En maintenance'), ('reserved', 'Réservé')], default='available', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
    ]
