# Generated by Django 6.0.8 on 2026-09-05 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proprietes', '0003_organization'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cree le'),
        ),
        migrations.AlterField(
            model_name='property',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis a jour le'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cree le'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cree le'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis a jour le'),
        ),
    ]
