# Generated by Django 6.0.1 on 2026-08-23 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('received_date', models.DateField()),
                ('status', models.CharField(choices=[('held', 'Conservé'), ('partial_refund', 'Remboursement partiel'), ('fully_refunded', 'Entièrement remboursé'), ('deducted', 'Déduit')], default='held', max_length=20)),
                ('refund_date', models.DateField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deductions', models.TextField(blank=True, help_text='Motif des déductions')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lease', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='Locations.lease')),
            ],
            options={
                'db_table': 'payments_deposit',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='Référence paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Date de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('partial', 'Partiel'), ('overdue', 'En retard'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Virement bancaire'), ('check', 'Chèque'), ('cash', 'Espèces'), ('card', 'Carte bancaire'), ('online', 'Paiement en ligne')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='payments/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Locations.lease')),
            ],
            options={
                'db_table': 'payments_payment',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='Paiements.payment')),
            ],
            options={
                'db_table': 'payments_paymentrecord',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['lease', 'status'], name='payments_pa_lease_i_bddf55_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['due_date', 'status'], name='payments_pa_due_dat_77bc99_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_date'], name='payments_pa_paid_da_aed7df_idx'),
        ),
    ]
