# Generated by Django 6.0.8 on 2026-09-05 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Locations', '0005_rename_leases_leas_organiz_e0b1f2_idx_leases_leas_organiz_6ea869_idx_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
                ('reference', models.CharField(max_length=50, verbose_name='Reference')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant recu')),
                ('payment_date', models.DateField(verbose_name='Date de paiement')),
                ('method', models.CharField(choices=[('cash', 'Especes'), ('bank_transfer', 'Virement bancaire'), ('check', 'Cheque'), ('card', 'Carte bancaire'), ('orange_money', 'Orange Money'), ('moov_money', 'Moov Money')], max_length=30, verbose_name='Mode de paiement')),
                ('external_reference', models.CharField(blank=True, help_text='Numero de transaction Orange Money ou Moov Money, avis de virement.', max_length=100, verbose_name='Reference externe')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_payments', to='Locations.lease', verbose_name='Bail')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Encaissement',
                'verbose_name_plural': 'Encaissements',
                'db_table': 'finance_payment',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
                ('kind', models.CharField(choices=[('rent', 'Loyer'), ('charges', 'Charges'), ('deposit', 'Depot de garantie'), ('fee', 'Frais'), ('other', 'Autre')], default='rent', max_length=20, verbose_name='Nature')),
                ('label', models.CharField(blank=True, max_length=200, verbose_name='Libelle')),
                ('period_start', models.DateField(verbose_name='Debut de periode')),
                ('period_end', models.DateField(verbose_name='Fin de periode')),
                ('due_date', models.DateField(verbose_name='Echeance')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant du')),
                ('status', models.CharField(choices=[('pending', 'A payer'), ('partial', 'Partiellement payee'), ('paid', 'Payee'), ('cancelled', 'Annulee')], default='pending', max_length=20, verbose_name='Statut')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_charges', to='Locations.lease', verbose_name='Bail')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Echeance',
                'verbose_name_plural': 'Echeances',
                'db_table': 'finance_rentcharge',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant impute')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organisation')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.payment', verbose_name='Encaissement')),
                ('rent_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.rentcharge', verbose_name='Echeance')),
            ],
            options={
                'verbose_name': 'Imputation',
                'verbose_name_plural': 'Imputations',
                'db_table': 'finance_paymentallocation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'payment_date'], name='finance_pay_organiz_209be1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['lease', 'payment_date'], name='finance_pay_lease_i_e7f0c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('organization', 'reference')},
        ),
        migrations.AddIndex(
            model_name='rentcharge',
            index=models.Index(fields=['organization', 'status'], name='finance_ren_organiz_75330a_idx'),
        ),
        migrations.AddIndex(
            model_name='rentcharge',
            index=models.Index(fields=['lease', 'due_date'], name='finance_ren_lease_i_4f6daf_idx'),
        ),
        migrations.AddIndex(
            model_name='rentcharge',
            index=models.Index(fields=['due_date', 'status'], name='finance_ren_due_dat_5d1bf1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rentcharge',
            unique_together={('lease', 'kind', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['organization', 'created_at'], name='finance_pay_organiz_947933_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentallocation',
            unique_together={('payment', 'rent_charge')},
        ),
    ]
