# Generated by Django 6.0.8 on 2026-09-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_alter_compte_devise'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='compte',
            field=models.ForeignKey(blank=True, help_text='Caisse, banque ou compte mobile ou la somme a ete versee.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encaissements_loyers', to='comptes.compte', verbose_name='Compte encaisseur'),
        ),
    ]
