# Generated by Django 6.0.8 on 2026-09-05 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
                ('role', models.CharField(choices=[('owner', 'Proprietaire'), ('manager', 'Gestionnaire'), ('agent', 'Agent'), ('accountant', 'Comptable')], default='agent', max_length=20, verbose_name='Role')),
                ('is_default', models.BooleanField(default=False, help_text="Organisation ouverte a la connexion si l'utilisateur en a plusieurs.", verbose_name='Organisation par defaut')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'db_table': 'organizations_membership',
                'ordering': ['organization__name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cree le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis a jour le')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Identifiant')),
                ('kind', models.CharField(choices=[('agency', 'Agence immobiliere'), ('owner', 'Proprietaire independant')], default='agency', max_length=20, verbose_name='Type')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#0ea5e9', max_length=20, verbose_name='Couleur principale')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('country', models.CharField(default='Mali', max_length=100, verbose_name='Pays')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('members', models.ManyToManyField(related_name='organizations', through='organizations.Membership', to=settings.AUTH_USER_MODEL, verbose_name='Membres')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'db_table': 'organizations_organization',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'is_active'], name='organizatio_user_id_9eceb5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('organization', 'user')},
        ),
    ]
