# Generated by Django 6.0.1 on 2026-08-23 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('lease', 'Contrat de location'), ('inspection', 'État des lieux'), ('receipt', 'Quittance'), ('diagnostic', 'Diagnostic'), ('insurance', 'Assurance'), ('legal', 'Document légal'), ('other', 'Autre')], max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('file_size', models.IntegerField(help_text='Taille en octets')),
                ('mime_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'category'], name='documents_d_owner_i_dd0bcf_idx'), models.Index(fields=['expires_at'], name='documents_d_expires_796a52_idx')],
            },
        ),
    ]
