# Generated by Django 6.0.1 on 2026-08-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comptes', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='ImmoPilot', max_length=100, verbose_name="Nom de l'application")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name="Logo de l'application")),
                ('primary_color', models.CharField(default='#0ea5e9', max_length=20, verbose_name='Couleur principale')),
            ],
            options={
                'verbose_name': 'Paramètre du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
