# Generated by Django 6.0.1 on 2026-08-23 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proprietes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de bail')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notice_period_days', models.IntegerField(default=90, help_text='Délai de préavis en jours')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel')], default='monthly', max_length=20)),
                ('payment_day', models.IntegerField(default=1, help_text='Jour de paiement du loyer (1-31)')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('expired', 'Expiré'), ('terminated', 'Terminé'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('document', models.FileField(blank=True, null=True, upload_to='leases/documents/')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(limit_choices_to={'role': 'tenant'}, on_delete=django.db.models.deletion.CASCADE, related_name='leases', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leases', to='Proprietes.unit')),
            ],
            options={
                'db_table': 'leases_lease',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('move_in', "État des lieux d'entrée"), ('move_out', 'État des lieux de sortie'), ('periodic', 'État des lieux périodique')], max_length=20)),
                ('inspection_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='inspections/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_conducted', to=settings.AUTH_USER_MODEL)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='Locations.lease')),
            ],
            options={
                'db_table': 'leases_inspection',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='LeaseTenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_tenants', to='Locations.lease')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leases_leasetenant',
            },
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['unit', 'status'], name='leases_leas_unit_id_d203d6_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['tenant', 'status'], name='leases_leas_tenant__9c2189_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['end_date'], name='leases_leas_end_dat_3ab4df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leasetenant',
            unique_together={('lease', 'tenant')},
        ),
    ]
