# Generated by Django 6.0.8 on 2026-09-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du dépôt'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='leases/documents/', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='end_date',
            field=models.DateField(verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='notice_period_days',
            field=models.IntegerField(default=90, help_text='Délai de préavis en jours', verbose_name='Délai de préavis (jours)'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='payment_day',
            field=models.IntegerField(default=1, help_text='Jour de paiement du loyer (1-31)', verbose_name='Jour de paiement'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='payment_frequency',
            field=models.CharField(choices=[('monthly', 'Mensuel'), ('quarterly', 'Trimestriel'), ('yearly', 'Annuel')], default='monthly', max_length=20, verbose_name='Fréquence de paiement'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='rent_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant du loyer'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Signé le'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='start_date',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('expired', 'Expiré'), ('terminated', 'Terminé'), ('cancelled', 'Annulé')], default='draft', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Mis à jour le'),
        ),
    ]
