# Generated by Django 6.0.8 on 2026-09-05 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Locations', '0004_alignement'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='lease',
            new_name='leases_leas_organiz_6ea869_idx',
            old_name='leases_leas_organiz_e0b1f2_idx',
        ),
        migrations.AlterField(
            model_name='inspection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='leasetenant',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization', verbose_name='Organisation'),
        ),
    ]
